# Generated by Django 5.2.3 on 2025-07-04 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0002_alter_birthrecord_gender_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'pharmacist'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pharmacy_license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of experience in pharmacy.')),
            ],
        ),
    ]
