# Generated by Django 5.2.3 on 2025-07-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0003_pharmacist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementOfficer',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'procurement_officer'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician'), ('radiologist', 'Radiologist'), ('patient', 'Patient'), ('receptionist', 'Receptionist'), ('procurement_officer', 'Procurement Officer')], default='patient', max_length=20),
        ),
    ]
