# Generated by Django 5.2.3 on 2025-07-04 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0004_procurementofficer_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('PASSWORD_CHANGE', 'Password Change'), ('OTHER', 'Other')], help_text='Type of action performed', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('model_name', models.CharField(blank=True, help_text="Name of the model affected (e.g., 'Patient', 'Doctor')", max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object affected', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action')),
                ('changes', models.JSONField(blank=True, help_text="JSON representation of changes (e.g., {'field': 'old_value' -> 'new_value'})", null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (can be null if system action)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
