# Generated by Django 5.2.3 on 2025-07-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0005_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortalityrecord',
            old_name='death_certified_by',
            new_name='certified_by',
        ),
        migrations.RenameField(
            model_name='mortalityrecord',
            old_name='notes',
            new_name='contributing_factors',
        ),
        migrations.AddField(
            model_name='medication',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum quantity to trigger reorder'),
        ),
        migrations.AddField(
            model_name='medication',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current quantity in stock'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='death_location',
            field=models.CharField(blank=True, choices=[('ward', 'In-patient Ward'), ('icu', 'ICU'), ('er', 'Emergency Room'), ('other', 'Other (specify)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='encounter',
            field=models.OneToOneField(blank=True, help_text='Encounter during which death occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_app.encounter'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name if patient record not linked', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='reported_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='patient',
            field=models.ForeignKey(help_text="Link to the mother's patient record", on_delete=django.db.models.deletion.CASCADE, related_name='birth_records', to='clinical_app.patient'),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='cause_of_death',
            field=models.TextField(help_text='Primary cause of death'),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='clinical_app.patient'),
        ),
    ]
