# Generated by Django 5.2.3 on 2025-07-05 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0006_rename_death_certified_by_mortalityrecord_certified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'lab_tech'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('license_number', models.CharField(help_text='Professional license number for the lab technician.', max_length=50, unique=True)),
                ('specialization', models.CharField(blank=True, choices=[('Phlebotomy', 'Phlebotomy'), ('Microbiology', 'Microbiology'), ('Clinical Chemistry', 'Clinical Chemistry'), ('Hematology', 'Hematology'), ('Pathology', 'Pathology'), ('Virology', 'Virology'), ('Molecular Biology', 'Molecular Biology'), ('Other', 'Other')], help_text='Area of expertise or specialization.', max_length=100, null=True)),
                ('shift_info', models.CharField(blank=True, choices=[('Morning', 'Morning Shift'), ('Afternoon', 'Afternoon Shift'), ('Full Day', 'Full Day Shift'), ('Night', 'Night Shift')], max_length=50, null=True)),
                ('lab_section_assigned', models.CharField(blank=True, help_text='The specific lab section they primarily work in.', max_length=100, null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Educational background, certifications, and other qualifications.', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', help_text='Current employment status of the lab technician.', max_length=20)),
            ],
            options={
                'verbose_name': 'Lab Technician',
                'verbose_name_plural': 'Lab Technicians',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Radiologist',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'radiologist'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('medical_license_number', models.CharField(help_text='Medical license number for the radiologist.', max_length=50, unique=True)),
                ('sub_specialization', models.CharField(blank=True, choices=[('Diagnostic Radiology', 'Diagnostic Radiology'), ('Interventional Radiology', 'Interventional Radiology'), ('Pediatric Radiology', 'Pediatric Radiology'), ('Neuroradiology', 'Neuroradiology'), ('Musculoskeletal Radiology', 'Musculoskeletal Radiology'), ('Cardiothoracic Radiology', 'Cardiothoracic Radiology'), ('Breast Imaging', 'Breast Imaging'), ('Nuclear Medicine', 'Nuclear Medicine'), ('Other', 'Other')], help_text='Specific area of radiology expertise (e.g., Neuroradiology).', max_length=100, null=True)),
                ('date_hired', models.DateField()),
                ('on_call_status', models.BooleanField(default=False, help_text='Indicates if the radiologist is currently on-call.')),
                ('preferred_modalities', models.JSONField(blank=True, help_text="List of preferred imaging modalities (e.g., ['MRI', 'CT', 'X-ray']).", null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Medical degrees, board certifications, and other qualifications.', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', help_text='Current employment status of the radiologist.', max_length=20)),
            ],
            options={
                'verbose_name': 'Radiologist',
                'verbose_name_plural': 'Radiologists',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'receptionist'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shift_info', models.CharField(blank=True, choices=[('Morning', 'Morning Shift'), ('Afternoon', 'Afternoon Shift'), ('Full Day', 'Full Day Shift'), ('Night', 'Night Shift')], help_text="Information about the receptionist's working shift.", max_length=50, null=True)),
                ('assigned_desk', models.CharField(blank=True, help_text='The desk or area they are typically assigned to.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Receptionist',
                'verbose_name_plural': 'Receptionists',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
