# Generated by Django 5.2.3 on 2025-07-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0007_labtechnician_radiologist_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='nursing_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
