# Generated by Django 5.2.3 on 2025-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0008_nurse_nursing_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(default=0, help_text='Years of experience as a doctor.'),
        ),
    ]
