# Generated by Django 5.2.3 on 2025-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0009_doctor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, help_text='Years of experience as a doctor.', null=True),
        ),
    ]
