# Generated by Django 5.2.3 on 2025-07-09 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0011_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(help_text="Patient's primary reason for the visit (in their own words if possible).", verbose_name='Chief Complaint')),
                ('history_of_present_illness', models.TextField(blank=True, help_text='Detailed chronological description of the chief complaint.', null=True, verbose_name='History of Present Illness (HPI)')),
                ('review_of_systems', models.TextField(blank=True, help_text='Systematic inquiry about symptoms in different body systems.', null=True, verbose_name='Review of Systems (ROS)')),
                ('physical_exam_findings', models.TextField(blank=True, help_text='Objective findings from the physical exam.', null=True, verbose_name='Physical Examination Findings')),
                ('assessment', models.TextField(help_text="Provider's medical impression and differential diagnoses.", verbose_name='Assessment')),
                ('plan', models.TextField(help_text='Proposed diagnostic, therapeutic, and management strategies.', verbose_name='Plan')),
                ('primary_diagnosis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Diagnosis (e.g., ICD-10 code and description)')),
                ('secondary_diagnoses', models.TextField(blank=True, help_text='Comma-separated list of additional diagnoses.', null=True, verbose_name='Secondary Diagnoses')),
                ('interventions_performed', models.TextField(blank=True, help_text='Details of any procedures, therapies, or specific interventions carried out.', null=True, verbose_name='Interventions/Procedures Performed')),
                ('medications_prescribed', models.TextField(blank=True, help_text='List of medications, dosage, frequency, and route.', null=True, verbose_name='Medications Prescribed/Administered')),
                ('follow_up_instructions', models.TextField(blank=True, help_text='Instructions given to the patient for follow-up care.', null=True, verbose_name='Follow-up Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_notes', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(help_text='The encounter this clinical note is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='clinical_app.encounter')),
            ],
            options={
                'verbose_name': 'Clinical Note',
                'verbose_name_plural': 'Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
