# Generated by Django 5.2.3 on 2025-07-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0012_clinicalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_status',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('final', 'Final'), ('differential', 'Differential'), ('ruled_out', 'Ruled Out'), ('resolved', 'Resolved')], default='provisional', help_text='Current status of the diagnosis (e.g., provisional, final).', max_length=20),
        ),
    ]
