# Generated by Django 5.2.3 on 2025-07-09 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0013_diagnosis_diagnosis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesummary',
            name='date_signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesummary',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casesummary',
            name='signed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_clinical_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casesummary',
            name='user_initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='casesummary',
            name='user_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/case_summaries/'),
        ),
    ]
