# Generated by Django 5.2.3 on 2025-07-10 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0014_casesummary_date_signed_casesummary_is_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to='clinical_app.doctor'),
        ),
        migrations.AlterField(
            model_name='imagingrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_requests_made', to='clinical_app.doctor'),
        ),
        migrations.AlterField(
            model_name='imagingresult',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_results_reported', to='clinical_app.radiologist'),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_requests_made', to='clinical_app.doctor'),
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_results_performed', to='clinical_app.labtechnician'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_history_entries', to='clinical_app.doctor'),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='examined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examinations_conducted', to='clinical_app.nurse'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_dispensed', to='clinical_app.pharmacist'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to='clinical_app.doctor'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans_created', to='clinical_app.doctor'),
        ),
    ]
