# Generated by Django 5.2.3 on 2025-07-10 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0015_alter_diagnosis_diagnosed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagingrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_requests_made_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagingresult',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_results_reported_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_requests_made_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_results_performed_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_history_recorded_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='examined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_examinations_examined_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_prescribed_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans_created_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
