# Generated by Django 5.2.3 on 2025-07-10 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0016_alter_diagnosis_diagnosed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='department',
            name='annual_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The allocated annual budget for this department. Useful for procurement tracking.', max_digits=12),
        ),
        migrations.AddField(
            model_name='department',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary email address for the department.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary phone number for direct departmental contact.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('Clinical', 'Clinical Services'), ('Administrative', 'Administrative Services'), ('Diagnostic', 'Diagnostic Services'), ('Support', 'Support Services'), ('Emergency', 'Emergency Services'), ('Surgical', 'Surgical Services')], default='Clinical', help_text='Category of the department (e.g., Clinical, Administrative).', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='floor_number',
            field=models.IntegerField(blank=True, help_text='The floor number where the department is located.', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='The lead or head of this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this department is currently operational and active.'),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, help_text="Physical location within the hospital (e.g., 'Ground Floor, East Wing', 'Building C, Level 2').", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='staff_count',
            field=models.IntegerField(blank=True, help_text='Approximate total number of staff members in the department.', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text="A brief overview of the department's functions and scope.", null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text="The official name of the department (e.g., 'Pediatrics', 'Radiology').", max_length=100, unique=True),
        ),
    ]
