# Generated by Django 5.2.3 on 2025-07-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0017_alter_department_options_department_annual_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='patient',
            field=models.OneToOneField(blank=True, help_text='The patient currently assigned to this bed. Null if bed is empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bed', to='clinical_app.patient'),
        ),
    ]
