# Generated by Django 5.2.3 on 2025-07-10 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0018_bed_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingresult',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
