# Generated by Django 5.2.3 on 2025-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0019_alter_imagingresult_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='route',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('iv', 'Intravenous (IV)'), ('im', 'Intramuscular (IM)'), ('sc', 'Subcutaneous (SC)'), ('topical', 'Topical'), ('rectal', 'Rectal'), ('vaginal', 'Vaginal'), ('inhalational', 'Inhalational'), ('sublingual', 'Sublingual')], max_length=50, null=True),
        ),
    ]
