# Generated by Django 5.2.3 on 2025-07-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0020_alter_prescription_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='consent_signatures/'),
        ),
    ]
