# Generated by Django 5.2.3 on 2025-07-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0021_consentform_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentform',
            name='digital_signature_hash',
        ),
        migrations.RemoveField(
            model_name='consentform',
            name='document_file',
        ),
    ]
