# Generated by Django 5.2.3 on 2025-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0022_remove_consentform_digital_signature_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='assigned_ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
