# Generated by Django 5.2.3 on 2025-07-13 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0023_nurse_assigned_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='assigned_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurses_assigned', to='clinical_app.ward'),
        ),
    ]
