# Generated by Django 5.2.3 on 2025-07-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0024_alter_nurse_assigned_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_beds', to='clinical_app.nurse'),
        ),
    ]
