# Generated by Django 5.2.3 on 2025-07-13 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0025_bed_assigned_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_managed', to='clinical_app.nurse'),
        ),
    ]
