# Generated by Django 5.2.3 on 2025-07-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0026_encounter_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, help_text='Years of experience in pharmacy.', null=True),
        ),
    ]
